<!-- Footer -->
<div class="container-fluid mt-4 text-white bg-clip-dark">

    <div class="container">

        <footer class="pt-4 pt-md-5 border-top text-white">
            <div class="row">

                <div class="col-12 col-md">
                    <img class="mb-2" src="assets/images/efcclogo.png" alt="" width="24" height="24">
                    <span style="font-weight: bold;">EFCC Academy</span>
                    <p>
                        Idoma Way, Federal Housing,Phase I,<br/>
                        Karu-Abuja, Nigeria.<br/>
                        <b>Tel:</b> +234 8138249537;<br/> +234 8132528643; <br/>+234 8095531194 <br/>
                        <b>P.O.Box:</b> 44, Karu;<br/> <b> Email:</b> academy@efccnigeria.org<br/>
                    </p>
                </div>

                <div class="col-6 col-md">
                    <h5>Research and Publication</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Activities</a></li>
                        <li><a class="text-muted" href="#">Achievements</a></li>
                        <li><a class="text-muted" href="#">Library</a></li>
                    </ul>
                </div>

                <div class="col-6 col-md">
                    <h5>Training</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Cadets</a></li>
                        <li><a class="text-muted" href="#">Certficated</a></li>
                        <li><a class="text-muted" href="#">Career Development</a></li>
                        <li><a class="text-muted" href="#">Training Units</a></li>
                    </ul>
                </div>
<!--
                <div class="col-6 col-md">
                    <h5>About</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Team</a></li>
                        <li><a class="text-muted" href="#">Locations</a></li>
                        <li><a class="text-muted" href="#">Privacy</a></li>
                        <li><a class="text-muted" href="#">Terms</a></li>
                    </ul>
                </div>
-->                

            </div>
        </footer>

    </div>

</div>
<!-- / Footer -->

<!-- Scroll to Top Button -->
<button class="scroll-top tran3s color2_bg" style="display: block;">
    <span class="fa fa-angle-up"></span>
</button>
<!-- / Scroll to Top Button -->

<!-- Copyright -->
<footer class="footer mt-auto py-3 bg-black text-center">
    <div class="container">
        <span class="text-muted">&copy; 2019 EFCC Academy. All Copyright Reserved.</span>
    </div>
</footer>
<!-- / Copyright -->